### ISSUE TITLE
Skapa en mockup databas i GO

### ISSUE THREAD

**Issue by mikaelSahlestrom** [INDAPlus20/sahlest-emilsjol-nodelius-project#38]
- [ ] Skapa en temporär/rudimentär "databas" i GO (en objektstruktur som kan modifieras baserat på API' post funktioner)
- [ ] Skriv om showMessage API't till att returnera "databasen" (Använder man showMessageLog API't så ska man få hela objektet ,detta ska senare kunna presenteras i frontend)

**Comment by NoraOdel** [comment]
Inte implimenterad
